export interface Service {
  id: string
  name: string
  nameEn: string
  nameEs: string
  description: string
  descriptionEn: string
  descriptionEs: string
  price: number
  originalPrice?: number
  duration?: string
  category: 'quick' | 'consultation' | 'special'
  subcategory?: 'love' | 'relations' | 'financial' | 'planning' | 'direction' | 'depth'
  isOffer?: boolean
  discountStart?: Date
  discountEnd?: Date
}

export const services: Service[] = [
  // Quick Answers
  {
    id: 'pergunta-objetiva',
    name: 'Pergunta Objetiva',
    nameEn: 'Objective Question',
    nameEs: 'Pregunta Objetiva',
    description: 'Pergunta de sim ou não com cleromancia (dados). Além da resposta direta, você recebe contexto claro.',
    descriptionEn: 'Yes-or-no question answered with cleromancy (dice). Beyond the direct answer, you receive clear context.',
    descriptionEs: 'Pregunta de sí o no respondida con cleromancia (dados). Además de la respuesta directa, recibes contexto claro.',
    price: 5.99,
    category: 'quick',
    isOffer: true,
  },
  {
    id: 'pergunta-detalhada',
    name: 'Pergunta Detalhada',
    nameEn: 'Detailed Question',
    nameEs: 'Pregunta Detallada',
    description: 'Leitura aprofundada para perguntas abertas e temas complexos, com análise completa e direcionamento prático pela cartomancia.',
    descriptionEn: 'In-depth reading for open questions and complex themes, with complete analysis and practical guidance through cartomancy.',
    descriptionEs: 'Lectura profunda para preguntas abiertas y temas complejos, con análisis completo y orientación práctica mediante cartomancia.',
    price: 9.99,
    category: 'quick',
  },
  
  // Full Consultations
  {
    id: 'consulta-30min',
    name: 'Consulta Completa 30min',
    nameEn: 'Full Consultation 30min',
    nameEs: 'Consulta Completa 30min',
    description: 'Leitura aprofundada com tempo para perguntas',
    descriptionEn: 'In-depth reading with time for questions',
    descriptionEs: 'Lectura profunda con tiempo para preguntas',
    price: 64.99,
    duration: '30 minutos',
    category: 'consultation',
  },
  {
    id: 'consulta-45min',
    name: 'Consulta Completa 45min',
    nameEn: 'Full Consultation 45min',
    nameEs: 'Consulta Completa 45min',
    description: 'Leitura completa com múltiplas tiragens',
    descriptionEn: 'Complete reading with multiple spreads',
    descriptionEs: 'Lectura completa con múltiples tiradas',
    price: 77.99,
    duration: '45 minutos',
    category: 'consultation',
  },
  {
    id: 'consulta-60min',
    name: 'Consulta Completa 60min',
    nameEn: 'Full Consultation 60min',
    nameEs: 'Consulta Completa 60min',
    description: 'Sessão extensa para questões complexas',
    descriptionEn: 'Extended session for complex questions',
    descriptionEs: 'Sesión extendida para cuestiones complejas',
    price: 99.99,
    duration: '60 minutos',
    category: 'consultation',
  },
  
  // Special Readings - Love
  {
    id: 'templo-afrodite',
    name: 'Templo de Afrodite (Casais)',
    nameEn: 'Temple of Aphrodite (Couples)',
    nameEs: 'Templo de Afrodita (Parejas)',
    description: 'Análise profunda do relacionamento atual',
    descriptionEn: 'Deep analysis of current relationship',
    descriptionEs: 'Análisis profundo de la relación actual',
    price: 29.99,
    category: 'special',
    subcategory: 'love',
  },
  {
    id: 'aurora-coracao',
    name: 'Aurora do Coração (Solteiros)',
    nameEn: 'Dawn of the Heart (Singles)',
    nameEs: 'Aurora del Corazón (Solteros)',
    description: 'Orientação para quem busca amor',
    descriptionEn: 'Guidance for those seeking love',
    descriptionEs: 'Orientación para quienes buscan amor',
    price: 29.99,
    category: 'special',
    subcategory: 'love',
  },
  {
    id: 'grande-mapa-amor',
    name: 'O Grande Mapa do Amor',
    nameEn: 'The Great Map of Love',
    nameEs: 'El Gran Mapa del Amor',
    description: 'Visão completa da vida amorosa',
    descriptionEn: 'Complete view of love life',
    descriptionEs: 'Visión completa de la vida amorosa',
    price: 54.99,
    category: 'special',
    subcategory: 'love',
  },
  {
    id: 'despertar-amor',
    name: 'O Despertar para o Amor',
    nameEn: 'Awakening to Love',
    nameEs: 'El Despertar al Amor',
    description: 'Desbloqueando padrões amorosos',
    descriptionEn: 'Unlocking love patterns',
    descriptionEs: 'Desbloqueando patrones amorosos',
    price: 54.99,
    category: 'special',
    subcategory: 'love',
  },
  {
    id: 'ficar-partir',
    name: 'Ficar ou Partir?',
    nameEn: 'Stay or Leave?',
    nameEs: '¿Quedarse o Irse?',
    description: 'Clareza para decisões difíceis no amor',
    descriptionEn: 'Clarity for difficult love decisions',
    descriptionEs: 'Claridad para decisiones difíciles en el amor',
    price: 34.99,
    category: 'special',
    subcategory: 'love',
  },
  {
    id: 'ponte-almas',
    name: 'A Ponte Entre Almas',
    nameEn: 'The Bridge Between Souls',
    nameEs: 'El Puente Entre Almas',
    description: 'Conexão espiritual entre duas pessoas',
    descriptionEn: 'Spiritual connection between two people',
    descriptionEs: 'Conexión espiritual entre dos personas',
    price: 44.99,
    category: 'special',
    subcategory: 'love',
  },
  {
    id: 'templo-diabo',
    name: 'Templo do Diabo',
    nameEn: 'Temple of the Devil',
    nameEs: 'Templo del Diablo',
    description: 'Explorando paixões e desejos ocultos',
    descriptionEn: 'Exploring hidden passions and desires',
    descriptionEs: 'Explorando pasiones y deseos ocultos',
    price: 44.99,
    category: 'special',
    subcategory: 'love',
  },
  
  // Special Readings - Relations
  {
    id: 'espelho-confianca',
    name: 'Espelho da Confiança',
    nameEn: 'Mirror of Trust',
    nameEs: 'Espejo de la Confianza',
    description: 'Análise de confiança em relacionamentos',
    descriptionEn: 'Trust analysis in relationships',
    descriptionEs: 'Análisis de confianza en relaciones',
    price: 29.99,
    category: 'special',
    subcategory: 'relations',
  },
  
  // Special Readings - Financial & Career
  {
    id: 'portal-novo-ciclo',
    name: 'O Portal do Novo Ciclo',
    nameEn: 'The Portal of the New Cycle',
    nameEs: 'El Portal del Nuevo Ciclo',
    description: 'Transição de carreira e novos começos',
    descriptionEn: 'Career transition and new beginnings',
    descriptionEs: 'Transición de carrera y nuevos comienzos',
    price: 29.99,
    category: 'special',
    subcategory: 'financial',
  },
  {
    id: 'despertar-vocacao',
    name: 'O Despertar da Vocação',
    nameEn: 'Awakening of Vocation',
    nameEs: 'El Despertar de la Vocación',
    description: 'Descobrindo seu propósito profissional',
    descriptionEn: 'Discovering your professional purpose',
    descriptionEs: 'Descubriendo tu propósito profesional',
    price: 39.99,
    category: 'special',
    subcategory: 'financial',
  },
  {
    id: 'salto-empreendedor',
    name: 'O Salto do Empreendedor',
    nameEn: 'The Entrepreneur\'s Leap',
    nameEs: 'El Salto del Emprendedor',
    description: 'Orientação para novos negócios',
    descriptionEn: 'Guidance for new businesses',
    descriptionEs: 'Orientación para nuevos negocios',
    price: 39.99,
    category: 'special',
    subcategory: 'financial',
  },
  {
    id: 'bussola-empreendedor',
    name: 'A Bússola do Empreendedor',
    nameEn: 'The Entrepreneur\'s Compass',
    nameEs: 'La Brújula del Emprendedor',
    description: 'Direcionamento para decisões empresariais',
    descriptionEn: 'Direction for business decisions',
    descriptionEs: 'Dirección para decisiones empresariales',
    price: 39.99,
    category: 'special',
    subcategory: 'financial',
  },
  {
    id: 'caminho-fortuna',
    name: 'Caminho da Fortuna',
    nameEn: 'Path of Fortune',
    nameEs: 'Camino de la Fortuna',
    description: 'Prosperidade e abundância financeira',
    descriptionEn: 'Prosperity and financial abundance',
    descriptionEs: 'Prosperidad y abundancia financiera',
    price: 49.99,
    category: 'special',
    subcategory: 'financial',
  },
  
  // Special Readings - Planning
  {
    id: 'bussola-semanal',
    name: 'Bússola Semanal',
    nameEn: 'Weekly Compass',
    nameEs: 'Brújula Semanal',
    description: 'Orientação para a semana',
    descriptionEn: 'Guidance for the week',
    descriptionEs: 'Orientación para la semana',
    price: 19.99,
    category: 'special',
    subcategory: 'planning',
  },
  {
    id: 'bussola-mensal',
    name: 'Bússola Mensal',
    nameEn: 'Monthly Compass',
    nameEs: 'Brújula Mensual',
    description: 'Planejamento mensal com os oráculos',
    descriptionEn: 'Monthly planning with the oracles',
    descriptionEs: 'Planificación mensual con los oráculos',
    price: 34.99,
    category: 'special',
    subcategory: 'planning',
  },
  
  // Special Readings - Direction
  {
    id: 'mandala-vida',
    name: 'Mandala da Vida',
    nameEn: 'Life Mandala',
    nameEs: 'Mandala de la Vida',
    description: 'Visão 360° de todas as áreas da vida',
    descriptionEn: '360° view of all life areas',
    descriptionEs: 'Visión 360° de todas las áreas de la vida',
    price: 59.99,
    category: 'special',
    subcategory: 'direction',
  },
  
  // Special Readings - Depth
  {
    id: 'cruz-celta',
    name: 'Cruz Celta',
    nameEn: 'Celtic Cross',
    nameEs: 'Cruz Celta',
    description: 'Tiragem clássica de 10 cartas',
    descriptionEn: 'Classic 10-card spread',
    descriptionEs: 'Tirada clásica de 10 cartas',
    price: 49.99,
    category: 'special',
    subcategory: 'depth',
  },
  {
    id: 'ferradura',
    name: 'Ferradura',
    nameEn: 'Horseshoe',
    nameEs: 'Herradura',
    description: 'Tiragem versátil de 7 cartas',
    descriptionEn: 'Versatile 7-card spread',
    descriptionEs: 'Tirada versátil de 7 cartas',
    price: 29.99,
    category: 'special',
    subcategory: 'depth',
  },
]

export const oracles = [
  {
    id: 'tarot',
    name: 'Tarot',
    description: 'O mais tradicional dos oráculos, com 78 cartas que revelam passado, presente e futuro.',
    descriptionEn: 'The most traditional oracle, with 78 cards that reveal past, present, and future.',
    descriptionEs: 'El oráculo más tradicional, con 78 cartas que revelan pasado, presente y futuro.',
  },
  {
    id: 'baralho-cigano',
    name: 'Baralho Cigano',
    description: 'Lenormand com 36 cartas, direto e objetivo, ideal para questões práticas.',
    descriptionEn: 'Lenormand with 36 cards, direct and objective, ideal for practical questions.',
    descriptionEs: 'Lenormand con 36 cartas, directo y objetivo, ideal para cuestiones prácticas.',
  },
  {
    id: 'sibilla',
    name: 'Sibilla',
    description: 'Oráculo italiano focado em relacionamentos e situações cotidianas.',
    descriptionEn: 'Italian oracle focused on relationships and everyday situations.',
    descriptionEs: 'Oráculo italiano enfocado en relaciones y situaciones cotidianas.',
  },
  {
    id: 'cleromancia',
    name: 'Cleromancia',
    description: 'Arte divinatória através de dados sagrados e sortes.',
    descriptionEn: 'Divinatory art through sacred dice and lots.',
    descriptionEs: 'Arte adivinatoria a través de dados sagrados y suertes.',
  },
]

export const faqItems = [
  {
    question: 'Como funciona uma consulta online?',
    questionEn: 'How does an online consultation work?',
    questionEs: '¿Cómo funciona una consulta online?',
    answer: 'As consultas são realizadas por chamada de vídeo ou áudio. Você escolhe o horário, realizamos a conexão e começamos a leitura. Tudo é feito em ambiente seguro e privado.',
    answerEn: 'Consultations are conducted via video or audio call. You choose the time, we connect, and begin the reading. Everything is done in a secure and private environment.',
    answerEs: 'Las consultas se realizan por videollamada o llamada de audio. Eliges el horario, nos conectamos y comenzamos la lectura. Todo se hace en un ambiente seguro y privado.',
  },
  {
    question: 'Preciso ter alguma pergunta específica?',
    questionEn: 'Do I need a specific question?',
    questionEs: '¿Necesito tener una pregunta específica?',
    answer: 'Não necessariamente. Podemos fazer uma leitura geral sobre sua vida ou focar em áreas específicas como amor, carreira ou espiritualidade.',
    answerEn: 'Not necessarily. We can do a general reading about your life or focus on specific areas like love, career, or spirituality.',
    answerEs: 'No necesariamente. Podemos hacer una lectura general sobre tu vida o enfocarnos en áreas específicas como amor, carrera o espiritualidad.',
  },
  {
    question: 'As previsões são definitivas?',
    questionEn: 'Are predictions definitive?',
    questionEs: '¿Las predicciones son definitivas?',
    answer: 'Os oráculos mostram tendências e possibilidades baseadas no momento presente. Você sempre tem o livre arbítrio para moldar seu futuro.',
    answerEn: 'Oracles show tendencies and possibilities based on the present moment. You always have free will to shape your future.',
    answerEs: 'Los oráculos muestran tendencias y posibilidades basadas en el momento presente. Siempre tienes libre albedrío para moldear tu futuro.',
  },
  {
    question: 'Como escolher o tipo de leitura?',
    questionEn: 'How to choose the type of reading?',
    questionEs: '¿Cómo elegir el tipo de lectura?',
    answer: 'Cada oráculo tem sua especialidade. Posso ajudá-lo a escolher o melhor método para sua pergunta durante nossa conversa inicial.',
    answerEn: 'Each oracle has its specialty. I can help you choose the best method for your question during our initial conversation.',
    answerEs: 'Cada oráculo tiene su especialidad. Puedo ayudarte a elegir el mejor método para tu pregunta durante nuestra conversación inicial.',
  },
]
